### PR TITLE
v1.0 Release

### PR DESCRIPTION
**Pull request by profxj**
This pull request will serve as the official release of
v1.0 of igmspec.  

Mainly documentation

Will include a test or two to get Travis going.

### CODE REVIEW

**Comment by astronomeara** [comment]
Issues:  

1)
Madzilla ->conda list "^python$|numpy|astropy$|scipy$|matplotlib|PyQT"
Illegal variable name.

individual calls to conda list work ok

2)
Recommend in the downloading the database section to emphasize that the database is rather large

3)  
Add a new HIRES grating for "ORIGINAL" which is the data prior to the red/blue cross disperser designation?

4)  
For KODIAQ:
kodetime = *total* exposure time of the co-added spectrum
kodwblue = starting wavelength
kodwred = ending wavelength
kodrelease = 1,2,3.... (1 = DR1, 2=DR2, etc)

**Comment by astronomeara** [comment]
Shall I merge? looks like you dealt with most of my requests

**Comment by profxj** [comment]
No, I’ll do this merge when it’s ready.  But thanks.

> On Jul 7, 2016, at 12:32 PM, astronomeara <notifications@github.com> wrote:
> 
> Shall I merge? looks like you dealt with most of my requests
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/pyigm/igmspec/pull/21#issuecomment-231183209>, or mute the thread <https://github.com/notifications/unsubscribe/AD0Bjca_8ZX7fFcouXj2V7gf6Z1KP9OGks5qTVRXgaJpZM4JGOV3>.
> 
> !DSPAM:826,577eae5872412594532435!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by astronomeara** [comment]
Impressive!  merging.

**Pull request merged**
