### PR TITLE
Refactoring private DB

### PR DESCRIPTION
**Pull request by profxj**
Many updates to the private DB codes

Also, refacotred the survey dict.

docs+Notebook+test

### CODE REVIEW

**Comment by astronomeara** [comment]
Have looked at the private_ingest notebook, looks fine to me.  Apologies for the delay.  Will test explicitly when home on larger machine with the current db.

**Comment by profxj** [comment]
Will be hard to test this one, but I'm happy
to help you do so with KODIAQ DR2.

**Comment by astronomeara** [comment]
I'll get KODIAQ DR2 into ingest form fairly soon, good idea.  Need more from me on this PR?

**Comment by profxj** [comment]
I think we're good.  Am likely to merge tomorrow although I should
have liked some comments from @jhennawi

**Comment by profxj** [comment]
Merging without @jhennawi

**Pull request merged**
