### PR TITLE
More columns for Meta

### PR DESCRIPTION
**Pull request by profxj**
Closer to a proper ver01

Some bug fixes in HD-LLS too..

### CODE REVIEW

**Comment by astronomeara** [comment]
What's the philosophy behind having MIKE vs MIKEb and MIKEr?

**Comment by profxj** [comment]
yeah, good question.  Right now it is because in HD-LLS I sometimes spiced the two 
instruments and sometimes did not.  Ideally, I would separate them (i.e. there would be no MIKE,
only MIKEb and MIKEr).

**Comment by astronomeara** [comment]
I would also separate them by default (and perhaps not allow the spliced ones in in the first place once a robust splice tool exists for the user as needed).  I don't think that keeps me from merging though.

**Comment by profxj** [comment]
A splice/stitch tool is on the way in linetools…  PR #234
----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/ <http://www.ucolick.org/~xavier/>
http://imps.ucolick.org/ <http://imps.ucolick.org/>
http://www.qpqsurvey.org/ <http://www.qpqsurvey.org/>
http://k1dm3.ucolick.org/ <http://k1dm3.ucolick.org/>
http://www.ucolick.org/~xavier/IDL/index.html <http://www.ucolick.org/~xavier/IDL/index.html>
https://github.com/profxj/xastropy <https://github.com/profxj/xastropy>

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Pull request merged**
